#!/bin/sh

echo "Cloning darknet"
git clone https://github.com/pjreddie/darknet
echo "Applying patches"
patch -p0 < darknet.patch

cd darknet # Switch to darknet dir

echo "Cloning weights"
wget https://pjreddie.com/media/files/darknet53.conv.74
echo "Clearing data"
rm -rf data/*
echo "Building darknet"
make
